Node.js version changed from 10.x to 8.x
Node.js version changed from 10.x to 8.x to see it sorts out below build error

> flatris@ build /home/vsts/work/1/s
> env-cmd next build web

Error: Failed to find .env file at default paths: [./.env,./.env.js,./.env.json]
    at getEnvFile (/home/vsts/work/1/s/node_modules/env-cmd/dist/get-env-vars.js:58:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)